[green_agent]
agentbeats_id = "019bc41c-6d9c-7010-b4ae-04f36cefdcce"
env = { LLM_API_KEY = "${LLM_API_KEY}", LLM_PROVIDER = "${LLM_PROVIDER}" }

[[participants]]
agentbeats_id = ""
name = "agent_1"
image = ""
env = {}

[[participants]]
agentbeats_id = ""
name = "agent_2"
image = ""
env = {}

[config]
# Evaluation parameters
evaluation_tiers = ["graph", "llm_judge"]  # tier 1 + tier 2
