[green_agent]
agentbeats_id = "019bc41c-6d9c-7010-b4ae-04f36cefdcce"
# image = "ghcr.io/qte77/agentbeats-greenagent:latest"
env = { LLM_API_KEY = "${LLM_API_KEY}", LLM_PROVIDER = "${LLM_PROVIDER}" }

[[participants]]
name = "agent_1"
agentbeats_id = "019bc7a8-7e9b-7611-b110-28c01e7e7221"
# image = "ghcr.io/qte77/agentbeats-purpleagent:latest"
env = {}

[[participants]]
name = "agent_2"
agentbeats_id = "019bc7a8-7e9b-7611-b110-28c01e7e7221"
# image = "ghcr.io/qte77/agentbeats-purpleagent:latest"
env = {}

[config]
# Evaluation parameters
evaluation_tiers = ["graph", "llm_judge"]  # tier 1 + tier 2
